### ISSUE TITLE
Support Multiple Crypto Payments

### ISSUE THREAD

**Issue by 9mido** [ydaniels/django-cryptocurrency-payment#2]
This is more of a question/feature request if it does not already exist.

How do you configure in settings and views acceptance of multiple cryptocurrencies? 

Something like this:

Bitcoin (BTC): `<Address>`
Bitcoin Cash (BCH): `<Address>`
Litecoin (LTC): `<Address>`
Ethereum (ETH): `<Address>`

etc.

Maybe give the user the option to choose which out of the 4 above they want to pay with? 

Otherwise, for something like a one time donation, what would the difference be if someone just lists all the addresses on the HTML page? I guess this library is best used for subscription payments with crypto as an alternative to stripe, correct?

**Comment by ydaniels** [comment]
Yes, you are right the library can be used for one time donation and subscription payments.

Currently the library only supports  BTC  but i plan to add more in the future.
 You can easily add more crypto currency by implementing a simple class with these methods:
```
generate_new_address
convert_from_fiat
convert_to_fiat
confirm_address_payment
```
  see  https://github.com/ydaniels/HD-Merchant-wallet/blob/1fd25445275e942240f45fb069fd1a2064ff3d85/merchant_wallet/backends/btc.py#L59
then activate the coin by adding it in your settings file
```
CRYPTOCURRENCY_PAYMENT = {
    "MYCOIN": {
        "CODE": "MYC",
         "ACTIVE": True,
        "BACKEND": "path.to.MYCOIN.Class",
         .,
         .,
         .
    }
 }
```
Returning  ` [key for key, value in CRYPTOCURRENCY_PAYMENT.items() if value["ACTIVE"] is True]` from settings in your view will list all the active currency.

For something like donation, passing the same index to generate_new_address would always return the same address or you can just override the method and return a single address every time.

**Comment by 9mido** [comment]
@ydaniels Thanks for the response it was helpful.

How would you handle / create subscription payments? For example, how would you create recurring payments on a monthly, yearly, weekly, daily. bi-weekly basis?

**Comment by ydaniels** [comment]
You can integrate it with https://github.com/ydaniels/drf-django-flexible-subscriptions to handle any form of subscription in your project. You can generate new  crypto payment when user subscription is about to expire and re-activate or extend subscription deactivation date when user pays.
