### ISSUE TITLE
Implement Bitpay and Coinbase Commerce

### ISSUE THREAD

**Issue by 9mido** [ydaniels/django-cryptocurrency-payment#3]
Not sure if Bitpay and Coinbase Commerce APIs would fit into this library or if they each deserve their own django libraries (separate might be better). But it would be nice to tie in these APIs into django more easily. Similar to how dj-stripe exists for Stripe. There are others besides these APIs that I did not mention that may also be worthwhile.

**Comment by ydaniels** [comment]
Yes Bitpay and Coinbase Commerce would need to have a separate  django library. 
This library is for running or owning your own cryptocurrency payment gateway like Bitpay and Coinbase Commerce in a simple and efficient way. The only difference is, there is no cash settlement option but your coins will be available on your local wallet.
