### ISSUE TITLE
Payments are not reflecting in the wallet

### ISSUE THREAD

**Issue by Michael-Lyon** [ydaniels/django-cryptocurrency-payment#7]
* Django Cryptocurrency Payment version:
* Django version:
* Python version:
* Operating System:

### Description
How do i make sure that payments are received?

### What I Did

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by ydaniels** [comment]
What wallet  are you using ? did you use the public master key from the wallet directly ?

**Comment by Michael-Lyon** [comment]
Yes I did.

**Comment by ydaniels** [comment]
What  wallet ?
