### ISSUE TITLE
Upgrading URLs

### ISSUE THREAD

**Issue by MrAcho420** [ydaniels/django-cryptocurrency-payment#8]
* Django Cryptocurrency Payment version: 0.1.1 (pretty sure)
* Django version: 4.0
* Python version: 3.10
* Operating System: Arch Linux

Hello I am a big fan of this project and wanted to add it to my test online store website that I am developing. After some digging I found out that the URLs use django's 2.0 system and I was wondering if anyone got them working in higher django version or can guide me on how to "upgrade" them.

Thanks for your time
-Alex

**Comment by knowledgecomputer2018** [comment]
hi 
change url to re_path in urls.py if content have regular expression .

re_path( r'^payment/(?P<pk>[a-f0-9]{8}-?[a-f0-9]{4}-?4[a-f0-9]{3}-?[89ab][a-f0-9]{3}-?[a-f0-9]{12})/$', views.CryptoPaymentDetailView.as_view(), name='crypto_payment_detail'),

good luck 
god willing
